-- ============================================================
-- Kutt: reemplaza los 10 negocios de prueba por los 5 reales.
-- Se puede ejecutar varias veces sin duplicar nada.
-- Ejecutalo en la base de datos de Aiven (defaultdb) con DBeaver o mysql.
-- Las contrasenas van cifradas con BCrypt (no se ven en texto).
-- Las coordenadas son aproximadas (centro de Paz de Ariporo); el admin puede
-- afinarlas en Ajustes > Mi negocio. Pasos completos: PASOS-DESPLIEGUE.txt
-- ============================================================
SET NAMES utf8mb4;
START TRANSACTION;

-- 1) Borrar los 10 negocios ficticios y todo lo que colgaba de ellos
DELETE FROM citas WHERE negocio_id IN (SELECT id FROM negocios WHERE admin_correo IN ('emilker@barbershop.com','contacto@nailsstudio.com','contacto@glowestetica.com','elrey@barbershop.com','unasydetalles@correo.com','oasis@spa.com','zen@spa.com','bambu@spa.com','pielperfecta@correo.com','renova@correo.com'));
DELETE FROM ventas WHERE negocio_id IN (SELECT id FROM negocios WHERE admin_correo IN ('emilker@barbershop.com','contacto@nailsstudio.com','contacto@glowestetica.com','elrey@barbershop.com','unasydetalles@correo.com','oasis@spa.com','zen@spa.com','bambu@spa.com','pielperfecta@correo.com','renova@correo.com'));
DELETE FROM productos WHERE negocio_id IN (SELECT id FROM negocios WHERE admin_correo IN ('emilker@barbershop.com','contacto@nailsstudio.com','contacto@glowestetica.com','elrey@barbershop.com','unasydetalles@correo.com','oasis@spa.com','zen@spa.com','bambu@spa.com','pielperfecta@correo.com','renova@correo.com'));
DELETE FROM barberos WHERE negocio_id IN (SELECT id FROM negocios WHERE admin_correo IN ('emilker@barbershop.com','contacto@nailsstudio.com','contacto@glowestetica.com','elrey@barbershop.com','unasydetalles@correo.com','oasis@spa.com','zen@spa.com','bambu@spa.com','pielperfecta@correo.com','renova@correo.com'));
DELETE FROM adicionales WHERE negocio_id IN (SELECT id FROM negocios WHERE admin_correo IN ('emilker@barbershop.com','contacto@nailsstudio.com','contacto@glowestetica.com','elrey@barbershop.com','unasydetalles@correo.com','oasis@spa.com','zen@spa.com','bambu@spa.com','pielperfecta@correo.com','renova@correo.com'));
DELETE FROM metodos_pago WHERE negocio_id IN (SELECT id FROM negocios WHERE admin_correo IN ('emilker@barbershop.com','contacto@nailsstudio.com','contacto@glowestetica.com','elrey@barbershop.com','unasydetalles@correo.com','oasis@spa.com','zen@spa.com','bambu@spa.com','pielperfecta@correo.com','renova@correo.com'));
DELETE FROM resenas WHERE negocio_id IN (SELECT id FROM negocios WHERE admin_correo IN ('emilker@barbershop.com','contacto@nailsstudio.com','contacto@glowestetica.com','elrey@barbershop.com','unasydetalles@correo.com','oasis@spa.com','zen@spa.com','bambu@spa.com','pielperfecta@correo.com','renova@correo.com'));
DELETE FROM favoritos WHERE negocio_id IN (SELECT id FROM negocios WHERE admin_correo IN ('emilker@barbershop.com','contacto@nailsstudio.com','contacto@glowestetica.com','elrey@barbershop.com','unasydetalles@correo.com','oasis@spa.com','zen@spa.com','bambu@spa.com','pielperfecta@correo.com','renova@correo.com'));
DELETE FROM negocios WHERE admin_correo IN ('emilker@barbershop.com','contacto@nailsstudio.com','contacto@glowestetica.com','elrey@barbershop.com','unasydetalles@correo.com','oasis@spa.com','zen@spa.com','bambu@spa.com','pielperfecta@correo.com','renova@correo.com');
DELETE FROM usuarios WHERE rol = 'ADMIN_NEGOCIO' AND correo IN ('emilker@barbershop.com','contacto@nailsstudio.com','contacto@glowestetica.com','elrey@barbershop.com','unasydetalles@correo.com','oasis@spa.com','zen@spa.com','bambu@spa.com','pielperfecta@correo.com','renova@correo.com');

-- 2) Cuentas de administrador de los negocios reales
INSERT INTO usuarios (nombre, correo, password_hash, rol) VALUES ('Kenia Yineth Quiquiva Mendivelso', 'quiquivakenia@gmail.com', '$2a$10$YJ35.YyaxtFIyB7h8fT57OUF4z0jDK0vlM9C2le6H6jRrzx1UJyy6', 'ADMIN_NEGOCIO') ON DUPLICATE KEY UPDATE nombre = VALUES(nombre), password_hash = VALUES(password_hash), rol = 'ADMIN_NEGOCIO';
INSERT INTO usuarios (nombre, correo, password_hash, rol) VALUES ('Barbers Estudio', 'barberstudio@gmail.com', '$2a$10$LNVy8Kp.hFNuO2uwGmykP.MQS3bJ.rH1aLVXHyzNxHqVsxPW0r8O2', 'ADMIN_NEGOCIO') ON DUPLICATE KEY UPDATE nombre = VALUES(nombre), password_hash = VALUES(password_hash), rol = 'ADMIN_NEGOCIO';
INSERT INTO usuarios (nombre, correo, password_hash, rol) VALUES ('Zarzamora', 'brayanjosua2005@gmail.com', '$2a$10$gIrx7ocLd78MHwVc.LTHi.jqoBl2mRClbaBq.nkCV1Zq1AEZIAMYC', 'ADMIN_NEGOCIO') ON DUPLICATE KEY UPDATE nombre = VALUES(nombre), password_hash = VALUES(password_hash), rol = 'ADMIN_NEGOCIO';
INSERT INTO usuarios (nombre, correo, password_hash, rol) VALUES ('Mekatos Colpaz', 'mekatos.co@hotmail.com', '$2a$10$BPwti4oTl3zI1ZmgBoDX6uu8JotSvwMucQyEjItc7yR0nPGBg2QJS', 'ADMIN_NEGOCIO') ON DUPLICATE KEY UPDATE nombre = VALUES(nombre), password_hash = VALUES(password_hash), rol = 'ADMIN_NEGOCIO';
INSERT INTO usuarios (nombre, correo, password_hash, rol) VALUES ('PosArt Dulces Mordiscos', 'posart.dulces@example.com', '$2a$10$8yBcSZSqABPrIb/uzIO8V.6LAhcLoqS4M6ZC1kdY23f0Q6AIzwaAq', 'ADMIN_NEGOCIO') ON DUPLICATE KEY UPDATE nombre = VALUES(nombre), password_hash = VALUES(password_hash), rol = 'ADMIN_NEGOCIO';

-- 3) Los negocios (primero se borran por si ya estaban, para no duplicar)
DELETE FROM negocios WHERE admin_correo IN ('quiquivakenia@gmail.com','barberstudio@gmail.com','brayanjosua2005@gmail.com','mekatos.co@hotmail.com','posart.dulces@example.com');
INSERT INTO negocios (nombre, rubro, telefono_fijo, departamento, direccion, logo_url, portada_url, admin_correo, verificado, latitud, longitud, servicio_nombre, servicio_precio, whatsapp, notificacion_destino) VALUES ('Kenia Brows & Lashes', 'ESTETICA', '+57 322 4746213', 'Casanare', 'Calle 7 #10-51, Paz de Ariporo', 'https://kutt-8ba8f.web.app/assets/negocios/kenia-logo.jpg', 'https://kutt-8ba8f.web.app/assets/negocios/kenia-portada.jpg', 'quiquivakenia@gmail.com', 1, 5.8836, -71.8829, 'Servicio base', 0, '573224746213', '');
INSERT INTO negocios (nombre, rubro, telefono_fijo, departamento, direccion, logo_url, portada_url, admin_correo, verificado, latitud, longitud, servicio_nombre, servicio_precio, whatsapp, notificacion_destino) VALUES ('Barbers Estudio', 'BARBERIA', '3219135551', 'Casanare', 'Calle 15 #7-20, Paz de Ariporo', 'https://kutt-8ba8f.web.app/assets/negocios/barbers-logo.jpg', 'https://kutt-8ba8f.web.app/assets/negocios/barbers-portada.jpg', 'barberstudio@gmail.com', 1, 5.883, -71.884, 'Servicio base', 0, '573219135551', '');
INSERT INTO negocios (nombre, rubro, telefono_fijo, departamento, direccion, logo_url, portada_url, admin_correo, verificado, latitud, longitud, servicio_nombre, servicio_precio, whatsapp, notificacion_destino) VALUES ('Zarzamora', 'OTRO', '3136043012', 'Casanare', 'Carrera 8 #4-74 Sur, El Progreso, Paz de Ariporo', 'https://kutt-8ba8f.web.app/assets/negocios/zarzamora-logo.jpg', 'https://kutt-8ba8f.web.app/assets/negocios/zarzamora-portada.jpg', 'brayanjosua2005@gmail.com', 1, 5.8826, -71.8825, 'Servicio base', 0, '573136043012', '');
INSERT INTO negocios (nombre, rubro, telefono_fijo, departamento, direccion, logo_url, portada_url, admin_correo, verificado, latitud, longitud, servicio_nombre, servicio_precio, whatsapp, notificacion_destino) VALUES ('Mekatos Colpaz', 'OTRO', '3208514037', 'Casanare', 'Carrera 10 #2-24, Paz de Ariporo', 'https://kutt-8ba8f.web.app/assets/negocios/mekatos-logo.jpg', 'https://kutt-8ba8f.web.app/assets/negocios/mekatos-portada.jpg', 'mekatos.co@hotmail.com', 1, 5.884, -71.8836, 'Servicio base', 0, '573208514037', '');
INSERT INTO negocios (nombre, rubro, telefono_fijo, departamento, direccion, logo_url, portada_url, admin_correo, verificado, latitud, longitud, servicio_nombre, servicio_precio, whatsapp, notificacion_destino) VALUES ('PosArt Dulces Mordiscos', 'OTRO', '3102911253', 'Casanare', 'Carrera 12 #12-64, Paz de Ariporo', NULL, NULL, 'posart.dulces@example.com', 1, 5.8832, -71.882, 'Servicio base', 0, '573102911253', '');

COMMIT;
